### ISSUE TITLE
Something wrong happened with Onedrive

### ISSUE THREAD

**Issue by Quorafind** [fxal/obsidian-youhavebeenstaring-plugin#6]
when I used Onedrive to sync plugin and data, something wrong happened with plugin
![image](https://user-images.githubusercontent.com/13215013/103966034-0247b780-519a-11eb-9d2b-8c12a4ea6d55.png)

It seems like the plugin continuously saves new data.json on local

**Comment by fxal** [comment]
Can confirm, currently it saves in each staring time increment. This also interfers with my automatic git commits of my vaults.
Will look into this, perhaps only save on unload or in fixed intervals.

**Comment by fxal** [comment]
Since there is no mechanism to execute a function when obsidian is shutting down, there will be an automatic save every 10 minutes.
Also on unload of the plugin.
And when you start/stop the counter with the ribbon button.
